# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(blank=True, max_length=99, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
