# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpiforimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snno', models.CharField(blank=True, max_length=2, null=True)),
                ('dpistyle', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
