# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='createtime',
            field=models.DateField(default='2017-06-17'),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
