# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_auto_20170612_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='createtime',
        ),
    ]
