# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0005_remove_video_createtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
