# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_remove_video_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='article',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='liker',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
