# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='belong_to',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
