# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_auto_20170612_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editors_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(default='/static/images/5.jpg', max_length=250),
        ),
    ]
