# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_auto_20170612_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.FileField(null=True, upload_to='cover_image'),
        ),
        migrations.AddField(
            model_name='article',
            name='url_img',
            field=models.URLField(default='/static/images/5.jpg', max_length=250),
        ),
    ]
