# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_auto_20170612_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
