# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_auto_20170617_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='choice',
            new_name='gerder_choice',
        ),
    ]
