# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('Tech', 'tech'), ('Life', 'life')], max_length=5, null=True),
        ),
    ]
