# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20171016_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Life', 'Life')], max_length=5, null=True),
        ),
    ]
