# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_article_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.AddField(
            model_name='article',
            name='mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
