# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(null=True, upload_to='url_image'),
        ),
    ]
