# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20170608_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('life', 'Life'), ('image', 'Image')], max_length=5, null=True),
        ),
    ]
