# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170608_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateField(),
        ),
    ]
