# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_auto_20170612_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_img',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
