# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20170610_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.URLField(default='static/images/default.png'),
        ),
        migrations.AddField(
            model_name='comment',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
