# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20170610_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='/static/images/default.png', max_length=200),
        ),
    ]
