# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_auto_20170617_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='realname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gerder_choice',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10),
        ),
    ]
