# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170905_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillstatus',
            name='Qstatus',
            field=models.CharField(choices=[('Red', 'red'), ('Yellow', 'yellow'), ('Green', 'green')], default='red', max_length=6),
        ),
        migrations.AlterField(
            model_name='multichoice',
            name='answer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='multistatus',
            name='Qstatus',
            field=models.CharField(choices=[('Red', 'red'), ('Yellow', 'yellow'), ('Green', 'green')], default='red', max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'mcq'), ('fill', 'fill'), ('code', 'code')], default='mcq', max_length=3),
        ),
    ]
