# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='choice',
            field=models.CharField(choices=[('gender', 'gender'), ('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
    ]
