# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_userprofile_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='choice',
            field=models.CharField(choices=[('gender', '性别'), ('male', '男'), ('female', '女')], default='male', max_length=10),
        ),
    ]
