# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_auto_20170618_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='firstapp.UserProfile'),
        ),
    ]
