# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_article_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='文章标题'),
        ),
    ]
